# Generated by Django 4.2.5 on 2023-09-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_alter_reply_content_alter_tweet_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(default='Chnage Model', max_length=10000),
            preserve_default=False,
        ),
    ]
